#!/bin/bash

echo "============================================"
echo " Command Line Tools 手动安装指南"
echo "============================================"
echo ""
echo "当前服务器: $(hostname)"
echo "架构: $(uname -m)"
echo ""

CLT_DIR="$HOME/commandline-tools"

if [ -d "$CLT_DIR" ]; then
    echo "✅ Command Line Tools 已安装"
    echo "   路径: $CLT_DIR"
    echo ""
    echo "SDK 内容:"
    ls -la "$CLT_DIR/sdk/openharmony" 2>/dev/null | head -10
    exit 0
fi

echo "❌ Command Line Tools 未安装"
echo ""
echo "============================================"
echo " 安装步骤"
echo "============================================"
echo ""
echo "【步骤 1】下载 Command Line Tools"
echo ""
echo "方式 A: 浏览器下载（推荐）"
echo "  1. 在本地电脑打开浏览器"
echo "  2. 访问: https://developer.huawei.com/consumer/cn/deveco-studio/"
echo "  3. 找到 'Command Line Tools' 下载区域"
echo "  4. 下载 Linux x64 版本"
echo "     文件名: commandline-tools-linux-x64-*.zip"
echo "     大小: 约 500MB"
echo ""
echo "方式 B: 服务器直接下载（需要 curl）"
echo "  在服务器执行:"
echo "  cd ~"
echo "  curl -L -o commandline-tools.zip '下载链接'"
echo "  （下载链接需要从华为开发者网站获取）"
echo ""
echo "============================================"
echo ""
echo "【步骤 2】上传到服务器"
echo ""
echo "在本地电脑执行（Windows PowerShell）:"
echo ""
echo "  scp commandline-tools-linux-x64-*.zip root@服务器IP:~/"
echo ""
echo "示例:"
echo "  scp commandline-tools-linux-x64-5.0.5.300.zip root@192.168.1.100:~/"
echo ""
echo "============================================"
echo ""
echo "【步骤 3】解压安装"
echo ""
echo "在服务器执行:"
echo ""
echo "  # 创建目录"
echo "  mkdir -p ~/commandline-tools"
echo ""
echo "  # 解压"
echo "  unzip ~/commandline-tools-linux-x64-*.zip -d ~/commandline-tools/"
echo ""
echo "  # 清理压缩包"
echo "  rm ~/commandline-tools-linux-x64-*.zip"
echo ""
echo "============================================"
echo ""
echo "【步骤 4】验证安装"
echo ""
echo "在服务器执行:"
echo ""
echo "  # 检查目录"
echo "  ls ~/commandline-tools/sdk/openharmony"
echo ""
echo "  # 应该看到类似输出:"
echo "  #  api  build-tools  native  ni  toolchains  ..."
echo ""
echo "============================================"
echo ""
echo "【步骤 5】继续构建"
echo ""
echo "安装完成后，重新运行构建脚本:"
echo ""
echo "  cd ~/x402-deveco"
echo "  ./build-docker-x86.sh"
echo ""
echo "============================================"
